apiVersion: v1
kind: Pod
metadata:
  name: basic-secret-pod
  namespace: default
  labels:
    name: secret-test
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: static-secret1
  containers:
  - name: secret-test-container
    image: busybox
    command: ["sh", "-c", "sleep 4800"]
    env:
      - 
        name: ENV_USER
        valueFrom:
          secretKeyRef:
            name: static-secret1
            key: user
      - 
        name: ENV_PASS
        valueFrom:
          secretKeyRef:
            name: static-secret1
            key: pass
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"