apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: default
  name: example
spec:
  vaultAuthRef: example
  mount: secret
  type: kv-v2
  path: vsodemo
  refreshAfter: 60s
  destination:
    create: true
    name: static-secret1