apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: default
  name: example
spec:
  # required configuration
  # address to the Vault server.
  address: "http://vault.vault.svc.cluster.local:8200"
  # skip TLS verification for TLS connections to Vault.
  skipTLSVerify: true